@startuml
' !theme vibrant
left to right direction

frame VintageCarCommunity {

package "AuthModule" {
    [Login] <<Component>>
    [Signup] <<Component>>
    [ForgotPassword] <<Component>>
    [VerifyEmail] <<Component>>
}

package "ProfilModule" {
    [Einlagerer] <<Component>>
    [Lagerhalter] <<Component>>
    [WerkstattInhaber] <<Component>>
    [Ersatzteilhandler] <<Component>>
}

package "SharedModule" {
    [Termin] <<Component>>
    [Anfrage] <<Component>>
    [Angebot] <<Component>>
    [Suche] <<Component>>
}

package "AppModule" {
    [Main] <<Component>>
    [App] <<Component>>
}

package "EinrichtungModule" {
    [Werkstatt] <<Component>>
    [Unternehmen] <<Component>>
}


package "LagerModule" {
    [Lager] <<Component>>
    [AddLager] <<Component>>
}

package "WareModule" {
    [ErsatzteilArtikel] <<Component>>
    [Service] <<Component>>
}

package "FahrzeugModule" {
    [Fahrzeug] <<Component>>
    [AddFahrzeug] <<Component>>
}

package "DashboardModule" {
    [Dashboard] <<Component>>
}

DashboardModule --[hidden]> ProfilModule
AppModule --[hidden]> FahrzeugModule
LagerModule --[hidden]> WareModule
WareModule --[hidden]> AppModule

}

@enduml