@startuml
!theme vibrant

rectangle VintageCarCommunity {

package "EinrichtungModul" {
    [Lager] <<Component>>
    [Werkstatt] <<Component>>
    [Unternehmen] <<Component>>
    [Stellplatz] <<Component>>
    [Servicezeiten] <<Model>>
    [Kondition] <<Enum>>
}

package "ProfilModule" {
    [Einlagerer] <<Component>>
    [Lagerhalter] <<Component>>
    [WerkstattInhaber] <<Component>>
    [Ersatzteilhandler] <<Enum>>
}


package "WareModule" {
    [ErsatzteilArtikel] <<Component>>
    [Service] <<Component>>
    [Artikelzustand] <<Enum>>
}

package "SharedModule" {
    [Termin] <<Component>>
    [Anfrage] <<Component>>
    [Angebot] <<Component>>
    [Suche] <<Component>>
    [Fahrzeug] <<Component>>
    [Ort] <<Model>>
    [AngebotStatus] <<Enum>>
    [Fahrzeugmarke] <<Enum>>
    [FahrzeugKategorie] <<Enum>>
}

}

@enduml