@startuml
abstract Benutzer {
  # Id : int
  # Vornahme : String
  # Nachname : String
  # MailAdresse : String
  SignUp()
  Login()
  UpdateProfil(Profil)
}

abstract  Einrichtung {
  # Id : int
  # Name : String
  # Ort : Ort
}

abstract Ware {
  # Id : int
  # Name : String
  # Beschreibung : String
  # Kosten : double
  AddWare(Ware)
  RemoveWare(Ware)
  EditWare(Ware)
  GetWare(id)
  GetWaren()

}

class Ort {
  - longitude : float
  - latitude : float
  - Strasse : String
  - Hausnummer : int
  - Zusatz : String
  - Plz : String
  - Stadt : String
  - Bundesland : String
}

class Lagerhalter {
  - Lager : List<Lager>
  AddLager(Lager)
  RemoveLager(id)
  EditLager(Lager)
}
class FahrzeugController{
GetFahrzeug(id)
GetFahrzeuge()
AddFahrzeug(Fahrzeug)
RemoveFahrzeug(id)
 EditFahrzeug(Fahrzeug)
}
class Einlagerer {
  - Fahrzeuge : List<Fahrzeug>

  CreateAnfrage(Lager)
  BookStellplatz(stellplatzId)
  SearchLager()
  RequestAngebot(Lager)
  SearchErsatzteile()
  BookService(Lager)
  ReserveArtikel(ArtikelId)
}

class WerkstattInhaber {
  - Werkstaette : List<Werkstaette>
  AddWerkstatt(Werkstatt)
  RemoveWerkstatt(id)
  EditWerkstatt(Werkstatt)
}

class Ersatzteilhandler {
  - Unternehmen : List<Unternehmen>
  AddUnternehmen(Unternehmen)
  RemoveUnternehmen(id)
  EditUnternehmen(Unternehmen)
}

class Stellplatz {
  + IstVerfuegbar : boolean
  - Massen : List<Double>
}

class Fahrzeug {
  - Id : int
  - Kategorie : FahrzeugKategorie
  - Marke : Fahrzeugmarke
  - Modell : String
  + IstFahrbereit : boolean
  + IstInWartung : boolean
  - Anmerkung : String
  AddAnmerkung(string)
}

class Termin {
  - Id : int
  - Beteiligte : List<Benutzer>
  - Ort : Ort
  - Datum : Date
  - Dauer : double
  - Zweck : String
  Book()
}

class Service {
-Anbieter : Benutzer
Book(Benutzer)
}

class Lager {
  - Id : int
  - Konditionen : List<Kondition>
  - Werkstaette : List<Werkstaette>
   + Services : List<Service>
  - Einlagerungsbetrag : double
  - Servicezeiten : List<Servicezeiten>
  - Stellplaetze : List<Stellplatz>
  - Kapazitaet : int
  - FreiePlaetze : int
  StoreFahrzeug(Fahrzeug, Stellplatz)
  CreateAngebot(Werkstatt)
}

class Servicezeiten {
  - Von : Date
  - Bis : Date
}

class ErsatzteilArtikel {
  - Zustand : Artikelzustand
  - IstReserviert : boolean
  MarkReserved()
  MarkAvalibale()
}

class Werkstatt {
  + Services : List<Service>
  + Fahrzeugmarken : List<Fahrzeugmarke>
}

class Unternehmen {
  - Waren : List<Ware>
}

class Anfrage {
  - Id : int
  - Von : Benutzer
  - An : Benutzer
  - Nachricht : String
  Send()
}

class Angebot {
  - Id : int
  - Anbieter : Benutzer
  - Kunde : Benutzer
  - Ware : Ware
  - Status : AngebotStatus
  - Betrag : double
  - Ablaufsdatum : Date
  Send()
  Accept()
  Reject()
}

enum AngebotStatus {
  Angenommen
  Abgelehnt
  Bevorstehend
}

enum Kondition {
  Beheizt
  UvGeschuetzt
  Klimatisiert
  ImmerZugaenglich
  Wachschutz
}

enum FahrzeugKategorie {
  Cabriolet
  Kleinstwagen
  Kleinwagen
  Kompaktklasse
  Mittelklasse
  ObereMittelklasse
  Luxus
  Suv
  Van
  }

enum Fahrzeugmarke {
  Porsche
  Bugatti
  Volkswagen
  MercedesBenz
  BMW
  Audi
  Opel
  Skoda
  Ford
  }

enum Artikelzustand {
  Neu
  Gebraucht
}


Benutzer <|-- Lagerhalter
Benutzer <|-- Einlagerer
Benutzer <|-- WerkstattInhaber
Benutzer <|-- Ersatzteilhandler

Lager -right-|> Einrichtung
Werkstatt -right-|> Einrichtung
Unternehmen -right-|> Einrichtung

Lagerhalter "1" *-- "1..*" Lager
Lagerhalter "*" -- "*" Werkstatt : arbeitet\nmit >
Lagerhalter "*" -- "*" Termin : vereinbart >
Lagerhalter "1" -up- "*" Angebot : macht >

WerkstattInhaber "1" *-- "1..*" Werkstatt

Ersatzteilhandler "1" *-- "1..*" Unternehmen
Unternehmen "1" -- "*" ErsatzteilArtikel : verkauft >

Einrichtung "1" -- "1" Ort : befindet\nsich\nam >
Termin "1" -- "1" Ort : findetstatt\nam >

Einlagerer "1" -- "*" Termin : vereinbart >


Lager "1" -- "1..*" Servicezeiten : ist\nverfügbar\nin  >
Lager "1" *-- "*" Kondition
Lager "1" -- "1..*" Stellplatz : verfügt\nüber >
Lager "1" -- "*" Service : bietet >

Fahrzeug "1" -- "1" FahrzeugKategorie : hat <
Fahrzeug "1" -- "1" Fahrzeugmarke : hat <

Fahrzeug "1" -- "1" Stellplatz : ist\nzugeordnet <
FahrzeugController "1" -- "*" Einlagerer : benutzt <
FahrzeugController "1" -- "*" Fahrzeug : verwaltet >

Einlagerer "1" *-left- "1..*" Fahrzeug
Einlagerer "1" -- "*" Lager : sucht <

Anfrage "*" -- "1" Einlagerer : schickt\nan\nLagerhalter <
Anfrage "*" -- "1" Lagerhalter : schickt\nan\nWerkstatt <

Werkstatt "1" -- "1..*" Service : bietet >

Service  --|> Ware
ErsatzteilArtikel  --|> Ware
Artikelzustand "1" -up- "1" ErsatzteilArtikel : beschreibt >
AngebotStatus "1" -left- "1" Angebot : beschreibt\nden Status\nvon <
@enduml